# FROM python:3.6
# LABEL maintainer="matheus.sasso17@gmail.com"

# # Install the C compiler tools
# RUN apt-get update -y && \
#   apt-get install build-essential -y && \
#   pip install --upgrade pip

# # Install libspatialindex
# WORKDIR /tmp
# RUN wget http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz && \
#   tar -xvzf spatialindex-src-1.8.5.tar.gz && \
#   cd spatialindex-src-1.8.5 && \
#   ./configure && \
#   make && \
#   make install && \
#   cd - && \
#   rm -rf spatialindex-src-1.8.5* && \
#   ldconfig

# # Install rtree and geopandas
# RUN pip install rtree geopandas

#FROM ubuntu:18.04
FROM osgeo/gdal:ubuntu-small-latest

LABEL maintainer="matheus.sasso17@gmail.com"

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
    build-essential \
    vim \
    chromium-browser \
    curl \
    libssl-dev \
    git \
    mercurial \
    pepperflashplugin-nonfree \
    libffi-dev \
    wget \
 && rm -rf /var/lib/apt/lists/*

# Create a working directory
WORKDIR /app/

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

# Install Miniconda and Python 3.8
ENV CONDA_AUTO_UPDATE_CONDA=false
ENV PATH=/home/user/miniconda/bin:$PATH
RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh \
 && chmod +x ~/miniconda.sh \
 && ~/miniconda.sh -b -p ~/miniconda \
 && rm ~/miniconda.sh \
 && conda install -y python==3.7.1 \
 && conda clean -ya

#RUN wget https://www.lfd.uci.edu/~gohlke/pythonlibs/#:~:text=GDAL%E2%80%913.3.3%E2%80%91cp37%E2%80%91cp37m%E2%80%91win32.whl
# RUN ls
# RUN pip install ./GDAL‑3.3.3‑cp37‑cp37m‑win32.whl
# RUN pip download GDAL
# RUN sudo python setup.py install --include-dirs=/usr/include/gdal
# RUN sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
# RUN sudo apt-get update
# RUN sudo apt-get install python-gdal


# # GDAL required pre installs
# RUN sudo apt-get update
# RUN sudo apt-get upgrade -y
# RUN sudo apt-get install -y software-properties-common
# RUN sudo apt-get install build-essential
# RUN sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update -y
# RUN sudo apt-get install gdal-bin -y
# RUN sudo apt-get install libgdal-dev -y
# ENV export CPLUS_INCLUDE_PATH=/usr/include/gdal
# ENV export C_INCLUDE_PATH=/usr/include/gdal
# RUN pip install GDAL

# # RUN sudo apt-get install build-essential python-all-dev
# # RUN sudo wget http://download.osgeo.org/gdal/2.2.2/gdal-2.2.2.tar.gz
# # RUN sudo tar xvfz gdal-2.2.2.tar.gz
# # WORKDIR gdal-2.2.2
# # RUN ./configure --with-python
# # RUN make
# # RUN make install
# # RUN cd ..

## Rasterio required pre installs
# RUN sudo add-apt-repository ppa:ubuntugis/ppa \
# && sudo apt-get update \
# && sudo apt-get install python-numpy gdal-bin libgdal-dev

#installing requirements

COPY ./wheels /app/wheels/
# COPY ./setup.py /app/setup.py
# COPY ./requirements.txt /app/requirements.txt
# RUN pip install -r /app/requirements.txt
RUN pip install /app/wheels/GDAL-3.3.3-cp37-cp37m-win32.whl

#Exposing Ports
EXPOSE 8080
EXPOSE 6006

# Entrypoint
ENTRYPOINT ["/bin/bash"]
CMD []
