FROM thinkwhere/gdal-python

LABEL maintainer="matheus.sasso17@gmail.com"

# Create a working directory
WORKDIR /app/

# RUN pip install --upgrade pip

# COPY ./setup.py /app/setup.py
# COPY ./requirements.txt /app/requirements.txt
# RUN pip install -r /app/requirements.txt

# RUN easy_install gdal
USER root

#Exposing Ports
EXPOSE 8080
EXPOSE 6006


# Entrypoint
ENTRYPOINT ["/bin/bash"]
CMD []
